// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyuxK_1kaOUD5O3PTEnuETpsmeer53zg8',
    appId: '1:666854488425:web:00c7b4bbcc026ac37225f8',
    messagingSenderId: '666854488425',
    projectId: 'mymemo-98f76',
    authDomain: 'mymemo-98f76.firebaseapp.com',
    storageBucket: 'mymemo-98f76.appspot.com',
    measurementId: 'G-DL4BMTGBFY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8zcCs0oeGlkAxoLJKSWHbiSBVs3WGux8',
    appId: '1:666854488425:android:0daa41bccab54d477225f8',
    messagingSenderId: '666854488425',
    projectId: 'mymemo-98f76',
    storageBucket: 'mymemo-98f76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRvjL92SaA1n-Jc4ql1WCyZf13D75FyOI',
    appId: '1:666854488425:ios:7ee15c2a13c6908d7225f8',
    messagingSenderId: '666854488425',
    projectId: 'mymemo-98f76',
    storageBucket: 'mymemo-98f76.appspot.com',
    iosClientId: '666854488425-eimcmu8m1iun2ifdf94c3ti6oa3vks03.apps.googleusercontent.com',
    iosBundleId: 'com.example.mymemoWithFlutterfire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyuxK_1kaOUD5O3PTEnuETpsmeer53zg8',
    appId: '1:666854488425:web:00c7b4bbcc026ac37225f8',
    messagingSenderId: '666854488425',
    projectId: 'mymemo-98f76',
    authDomain: 'mymemo-98f76.firebaseapp.com',
    storageBucket: 'mymemo-98f76.appspot.com',
    measurementId: 'G-DL4BMTGBFY',
  );
}
